import fs from "node:fs";
import path from "node:path";
import { createDualBuildVitePlugin, defineAdapter, type AdapterBuildContext } from "@otok/config";

export interface CloudflareAdapterOptions {
  outDir?: string;
  /** Wrangler project name. Defaults to the package directory name. */
  wranglerName?: string;
  /** Compatibility date for generated wrangler.toml. */
  compatibilityDate?: string;
  /** Project-relative worker entry. Generated when omitted. */
  workerEntry?: string;
  /** Client entry path passed to createOtokWorkerApp. */
  clientEntry?: string;
  /**
   * Cloudflare KV binding name used for HTML response caching via `EdgeKvCacheProvider`.
   * When set, wrangler.toml gets a `[[kv_namespaces]]` stub and the worker wires the provider per request.
   */
  cacheKvBinding?: string;
}

const CF_CAPABILITIES = [
  "ssr",
  "streaming",
  "middleware",
  "server-actions",
  "islands",
  "static-assets",
  "env-bindings",
  "worker-fetch",
] as const;

const DEFAULT_OUT_DIR = "dist";
const GENERATED_WORKER_ENTRY = "src/otok.generated.worker.ts";

function outputDirs(options: CloudflareAdapterOptions) {
  const root = options.outDir ?? DEFAULT_OUT_DIR;
  return {
    root,
    client: path.posix.join(root, "client"),
    server: path.posix.join(root, "server"),
  };
}

function generatedWorkerSource(options: CloudflareAdapterOptions): string {
  const clientEntry = options.clientEntry ?? "src/client.ts";
  const kvBinding = options.cacheKvBinding;

  const cacheImports = kvBinding
    ? `\nimport { setCacheProvider, EdgeKvCacheProvider } from "otok/cache";`
    : "";

  const fetchWrapper = kvBinding
    ? `
type Env = {
  ${kvBinding}: {
    get(key: string, type?: "text"): Promise<string | null>;
    put(key: string, value: string, options?: { expirationTtl?: number }): Promise<void>;
    delete(key: string): Promise<void>;
  };
  ASSETS?: Fetcher;
};

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    setCacheProvider(new EdgeKvCacheProvider({ namespace: env.${kvBinding} }));
    return app.fetch(request, env, ctx);
  },
};
`
    : `
export default app;
`;

  return `import { createOtokWorkerApp, resolveOtokManifest, type ViteManifest } from "otok/server";
import { errorRoute, notFoundRoute, routes } from "virtual:otok-routes";
import clientManifest from "../dist/client/.vite/manifest.json";${cacheImports}

/**
 * Cloudflare Worker entry generated by otok-adapter-cloudflare.
 * Hashed assets are served from Workers Assets (see wrangler.toml).
 */
const app = createOtokWorkerApp({
  routes,
  notFoundRoute,
  errorRoute,
  manifest: resolveOtokManifest(clientManifest as ViteManifest, { prodOnly: false }),
  clientEntry: ${JSON.stringify(clientEntry)},
  health: { ok: true, runtime: "cloudflare", adapter: "otok-adapter-cloudflare" },
  streaming: true,
});
${fetchWrapper}`;
}

function generatedWranglerToml(options: CloudflareAdapterOptions, ctx: AdapterBuildContext): string {
  const outDirs = outputDirs(options);
  const name = options.wranglerName ?? path.basename(ctx.root);
  const compatibilityDate = options.compatibilityDate ?? "2025-04-01";
  const kvBinding = options.cacheKvBinding;

  const kvSection = kvBinding
    ? `
# HTML response cache (replace id after wrangler kv namespace create)
[[kv_namespaces]]
binding = ${JSON.stringify(kvBinding)}
id = "REPLACE_WITH_KV_NAMESPACE_ID"
`
    : "";

  return `name = ${JSON.stringify(name)}
main = ${JSON.stringify(path.posix.join(outDirs.server, "server.js"))}
compatibility_date = ${JSON.stringify(compatibilityDate)}

# Hashed Vite client assets. HTML is rendered by the Worker.
[assets]
directory = ${JSON.stringify(`./${outDirs.client}`)}
binding = "ASSETS"
${kvSection}`;
}

async function writeGeneratedArtifacts(ctx: AdapterBuildContext, options: CloudflareAdapterOptions): Promise<void> {
  if (!options.workerEntry) {
    const workerPath = path.resolve(ctx.root, GENERATED_WORKER_ENTRY);
    fs.mkdirSync(path.dirname(workerPath), { recursive: true });
    fs.writeFileSync(workerPath, generatedWorkerSource(options));
  }

  const wranglerPath = path.resolve(ctx.root, "wrangler.toml");
  fs.writeFileSync(wranglerPath, generatedWranglerToml(options, ctx));
}

const cloudflareAdapterFactory = defineAdapter<CloudflareAdapterOptions>({
  name: "otok-adapter-cloudflare",
  runtime: "cloudflare",
  capabilities: CF_CAPABILITIES,
  build: {
    clientEntry: "src/client.ts",
    ssrEntry: GENERATED_WORKER_ENTRY,
    ssrTarget: "webworker",
    bundleDeps: true,
    clientManifest: true,
  },
  outputDirs(options, _root) {
    return outputDirs(options);
  },
  serverEntry(ctx) {
    const options = ctx.options as CloudflareAdapterOptions;
    const entry = options.workerEntry ?? GENERATED_WORKER_ENTRY;
    return { path: entry, generated: !options.workerEntry };
  },
  assets: {
    assetsPath: "/assets",
  },
  environment: {
    bindings: true,
  },
  ssr: {
    supported: true,
    streaming: true,
  },
  middleware: {
    supported: true,
  },
  prerender: {
    supported: false,
  },
  hooks: {
    async buildStart(ctx) {
      await writeGeneratedArtifacts(ctx, ctx.adapter.options as CloudflareAdapterOptions);
    },
    async buildEnd(ctx) {
      if (!ctx.isSsrBuild) return;
      await writeGeneratedArtifacts(ctx, ctx.adapter.options as CloudflareAdapterOptions);
    },
  },
  configureVite(ctx) {
    const options = ctx.options as CloudflareAdapterOptions;
    const outDirs = outputDirs(options);
    const workerEntry = options.workerEntry ?? GENERATED_WORKER_ENTRY;

    return createDualBuildVitePlugin({
      name: "otok-adapter-cloudflare",
      outDirs,
      build: {
        clientEntry: options.clientEntry ?? "src/client.ts",
        ssrEntry: workerEntry,
        ssrTarget: "webworker",
        bundleDeps: true,
        clientManifest: true,
      },
    });
  },
});

/** Cloudflare Workers adapter with worker-safe bundles and Workers Assets. */
export default function cloudflare(options: CloudflareAdapterOptions = {}) {
  return cloudflareAdapterFactory(options);
}

export {
  cloudflare,
  cloudflareAdapterFactory,
  GENERATED_WORKER_ENTRY,
  generatedWorkerSource,
  generatedWranglerToml,
  outputDirs as cloudflareOutputDirs,
};
