/* eslint-disable */
// @generated by @otok/route-typegen — do not edit manually.

/// <reference path="./src/app/routes/index.d.ts" />
/// <reference path="./src/app/routes/about.d.ts" />
/// <reference path="./src/app/routes/admin/index.d.ts" />
/// <reference path="./src/app/routes/boom.d.ts" />
/// <reference path="./src/app/routes/crash.d.ts" />
/// <reference path="./src/app/routes/deferred-demo.d.ts" />
/// <reference path="./src/app/routes/demo.d.ts" />
/// <reference path="./src/app/routes/docs/[...slug].d.ts" />
/// <reference path="./src/app/routes/projects.d.ts" />
/// <reference path="./src/app/routes/strategies.d.ts" />
/// <reference path="./src/app/routes/users/[id].d.ts" />
/// <reference path="./src/app/routes/_not-found.d.ts" />
/// <reference path="./src/app/routes/_error.d.ts" />
