/* eslint-disable */
// @generated by @kamod-ch/otok-route-typegen — do not edit manually.

declare module "virtual:otok-routes" {
  export type OtokRouteFilePattern = "/crm/companies/[id]" | "/about" | "/admin" | "/boom" | "/crash" | "/crm" | "/deferred-demo" | "/demo" | "/projects" | "/strategies" | "/users/[id]" | "/" | "/docs/[...slug]";
  export type OtokRoutePath = "/crm/companies/:id" | "/about" | "/admin" | "/boom" | "/crash" | "/crm" | "/deferred-demo" | "/demo" | "/projects" | "/strategies" | "/users/:id" | "/" | "/docs/:slug*";
  export type OtokRouteParams<Path extends OtokRouteFilePattern> = Path extends infer P extends string
    ? import("@kamod-ch/otok/route").RouteParamsFromPattern<P>
    : never;
  export type OtokRouteOptions<Path extends OtokRouteFilePattern> = import("@kamod-ch/otok/route").RouteBuildOptionsFor<Path>;
}

declare module "virtual:otok-route-redirect" {
  export type RedirectTarget = "/crm/companies/:id" | "/about" | "/admin" | "/boom" | "/crash" | "/crm" | "/deferred-demo" | "/demo" | "/projects" | "/strategies" | "/users/:id" | "/" | "/docs/:slug*" | import("virtual:otok-routes").OtokRouteFilePattern;
}

export interface OtokRouteManifest {
  root: "/home/watzak/master/kamod/otok/apps/playground";
  routesDir: "src/app/routes";
  patterns: readonly import("virtual:otok-routes").OtokRouteFilePattern[];
  paths: readonly import("virtual:otok-routes").OtokRoutePath[];
}
