import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import type { RouteEntry, RoutesScanResult } from "./parser.js";
import { routePatternsForScan, scanRoutes } from "./parser.js";
import { analyzeRoutes, formatRouteIssues } from "./conflicts.js";
import { detectSearchParamsSchemaName, uniqueRoutesByFile } from "./params.js";
import { normalizePath } from "./normalize-path.js";

export interface RouteTypegenOptions {
  root: string;
  routesDir?: string;
  outputDir?: string;
  /** Fail when route conflicts are detected. Default: true in CI mode. */
  strict?: boolean;
}

export interface RouteTypegenResult {
  ok: boolean;
  outputDir: string;
  files: string[];
  issues: ReturnType<typeof analyzeRoutes>["issues"];
  manifestHash: string;
  changed: boolean;
}

const GENERATED_BANNER = `/* eslint-disable */
// @generated by @kamod-ch/otok-route-typegen — do not edit manually.
`;

function stableHash(content: string): string {
  return crypto.createHash("sha256").update(content).digest("hex").slice(0, 16);
}

function moduleSpecifier(root: string, file: string): string {
  const relative = normalizePath(path.relative(root, file)).replace(/\.[cm]?tsx?$/, "");
  return `./${relative}`;
}

function importPath(fromDir: string, targetFile: string): string {
  let relative = normalizePath(path.relative(fromDir, targetFile)).replace(/\.[cm]?tsx?$/, "");
  if (!relative.startsWith(".")) relative = `./${relative}`;
  return relative;
}

function readRouteSource(file: string): string {
  try {
    return fs.readFileSync(file, "utf8");
  } catch {
    return "";
  }
}

function typeOutputPath(outputDir: string, route: RouteEntry, root: string): string {
  const relative = normalizePath(path.relative(root, route.file)).replace(/\.[cm]?tsx?$/, ".d.ts");
  return path.join(outputDir, relative);
}

function paramsTypeFromRoutePath(routePath: string, routePattern: string): string {
  const segments = routePattern.split("/").filter(Boolean);
  const fields: string[] = [];

  for (const segment of segments) {
    const catchAll = /^\[\.\.\.([^\]]+)\]$/.exec(segment);
    if (catchAll) {
      fields.push(`${catchAll[1]}: string | string[]`);
      continue;
    }
    const optional = /^\[\[([^\]]+)\]\]$/.exec(segment);
    if (optional) {
      const inPath = routePath.includes(`/:${optional[1]}`);
      fields.push(inPath ? `${optional[1]}: string` : `${optional[1]}?: string`);
      continue;
    }
    const dynamic = /^\[([^\]]+)\]$/.exec(segment);
    if (dynamic) fields.push(`${dynamic[1]}: string`);
  }

  return fields.length > 0 ? `{ ${fields.join("; ")} }` : "Record<string, never>";
}

function generateRouteModuleTypes(
  route: RouteEntry,
  root: string,
  moduleImportPath: string,
  source: string,
): string {
  const paramsType = paramsTypeFromRoutePath(route.routePath, route.routePattern);
  const searchExport = detectSearchParamsSchemaName(source);
  const searchParamsType = searchExport
    ? `ExtractSearchParams<typeof RouteModule.${searchExport}>`
    : "Record<string, string | string[] | undefined>";

  return `${GENERATED_BANNER}
import type * as RouteModule from "${moduleImportPath}";
import type {
  ExtractActionData,
  ExtractActionInput,
  ExtractLoaderData,
  ExtractMeta,
  ExtractSearchParams,
  RouteComponentProps,
  RouteErrorProps,
} from "otok/route";

declare module "${moduleSpecifier(root, route.file)}" {
  export namespace Route {
    export type FilePattern = ${JSON.stringify(route.routePattern)};
    export type Path = ${JSON.stringify(route.routePath)};
    export type Params = ${paramsType};
    export type SearchParams = ${searchParamsType};
    export type LoaderData = ExtractLoaderData<typeof RouteModule.loader>;
    export type ActionInput = ExtractActionInput<typeof RouteModule.action>;
    export type ActionData = ExtractActionData<typeof RouteModule.action>;
    export type Meta = ExtractMeta<typeof RouteModule.head, typeof RouteModule.meta>;
    export type ComponentProps = RouteComponentProps<LoaderData, ActionData, Params>;
    export type ErrorProps = RouteErrorProps<LoaderData, Params>;
    export type LayoutData = LoaderData;
    export type ParentData = Record<string, unknown>;
  }
}
`;
}

function generateManifestTypes(scan: RoutesScanResult, root: string, routesDir: string): string {
  const patterns = routePatternsForScan(scan);
  const resolvedPaths = [...new Set(scan.routes.map((route) => route.routePath))];
  const patternLiterals = patterns.map((pattern) => JSON.stringify(pattern)).join(" | ") || '"/"';
  const pathLiterals = resolvedPaths.map((routePath) => JSON.stringify(routePath)).join(" | ") || '"/"';

  return `${GENERATED_BANNER}
declare module "virtual:otok-routes" {
  export type OtokRouteFilePattern = ${patternLiterals};
  export type OtokRoutePath = ${pathLiterals};
  export type OtokRouteParams<Path extends OtokRouteFilePattern> = Path extends infer P extends string
    ? import("otok/route").RouteParamsFromPattern<P>
    : never;
  export type OtokRouteOptions<Path extends OtokRouteFilePattern> = import("otok/route").RouteBuildOptionsFor<Path>;
}

declare module "virtual:otok-route-redirect" {
  export type RedirectTarget = ${pathLiterals} | import("virtual:otok-routes").OtokRouteFilePattern;
}

export interface OtokRouteManifest {
  root: ${JSON.stringify(root)};
  routesDir: ${JSON.stringify(routesDir)};
  patterns: readonly import("virtual:otok-routes").OtokRouteFilePattern[];
  paths: readonly import("virtual:otok-routes").OtokRoutePath[];
}
`;
}

function generateIndexReference(files: string[], outputDir: string): string {
  const references = files
    .map((file) => {
      const rel = normalizePath(path.relative(outputDir, file));
      return `/// <reference path="./${rel}" />`;
    })
    .join("\n");

  return `${GENERATED_BANNER}
${references}
`;
}

function writeIfChanged(file: string, content: string): boolean {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const existing = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
  if (existing === content) return false;
  fs.writeFileSync(file, content, "utf8");
  return true;
}

export function generateRouteTypes(scan: RoutesScanResult, options: RouteTypegenOptions): RouteTypegenResult {
  const root = path.resolve(options.root);
  const routesDir = options.routesDir ?? "src/app/routes";
  const outputDir = path.resolve(root, options.outputDir ?? ".otok/types");
  const analysis = analyzeRoutes(scan);
  const strict = options.strict ?? process.env.CI === "true";

  if (strict && !analysis.ok) {
    throw new Error(formatRouteIssues(analysis.issues));
  }

  const writtenFiles: string[] = [];
  let changed = false;
  const uniqueRoutes = uniqueRoutesByFile(scan.routes);

  for (const route of uniqueRoutes) {
    const outputFile = typeOutputPath(outputDir, route, root);
    const moduleImportPath = importPath(path.dirname(outputFile), route.file);
    const content = generateRouteModuleTypes(route, root, moduleImportPath, readRouteSource(route.file));
    if (writeIfChanged(outputFile, content)) changed = true;
    writtenFiles.push(outputFile);
  }

  for (const special of [scan.notFoundRoute, scan.errorRoute]) {
    if (!special) continue;
    const outputFile = typeOutputPath(outputDir, special, root);
    const moduleImportPath = importPath(path.dirname(outputFile), special.file);
    const content = generateRouteModuleTypes(special, root, moduleImportPath, readRouteSource(special.file));
    if (writeIfChanged(outputFile, content)) changed = true;
    writtenFiles.push(outputFile);
  }

  const manifestFile = path.join(outputDir, "manifest.d.ts");
  if (writeIfChanged(manifestFile, generateManifestTypes(scan, root, routesDir))) changed = true;
  writtenFiles.push(manifestFile);

  const indexFile = path.join(outputDir, "index.d.ts");
  const routeTypeFiles = writtenFiles.filter((file) => file !== manifestFile && file !== indexFile);
  if (writeIfChanged(indexFile, generateIndexReference(routeTypeFiles, outputDir))) changed = true;
  writtenFiles.push(indexFile);

  const manifestHash = stableHash(
    [...writtenFiles]
      .sort()
      .map((file) => fs.readFileSync(file, "utf8"))
      .join("\n---\n"),
  );

  const hashFile = path.join(outputDir, ".hash");
  if (writeIfChanged(hashFile, `${manifestHash}\n`)) changed = true;

  return {
    ok: analysis.ok,
    outputDir,
    files: writtenFiles,
    issues: analysis.issues,
    manifestHash,
    changed,
  };
}

export function runRouteTypegen(options: RouteTypegenOptions): RouteTypegenResult {
  const scan = scanRoutes({ root: options.root, routesDir: options.routesDir ?? "src/app/routes" });
  return generateRouteTypes(scan, options);
}
