/* eslint-disable */
// @generated by @kamod-ch/otok-route-typegen — do not edit manually.

/// <reference path="./src/app/routes/index.d.ts" />
/// <reference path="./src/app/routes/articles/index.d.ts" />
/// <reference path="./src/app/routes/articles/[slug].d.ts" />
/// <reference path="./src/app/routes/login.d.ts" />
