/* eslint-disable */
// @generated by @kamod-ch/otok-route-typegen — do not edit manually.

declare module "virtual:otok-routes" {
  export type OtokRouteFilePattern = "/articles" | "/login" | "/articles/[slug]" | "/";
  export type OtokRoutePath = "/articles" | "/login" | "/articles/:slug" | "/";
  export type OtokRouteParams<Path extends OtokRouteFilePattern> = Path extends infer P extends string
    ? import("@kamod-ch/otok/route").RouteParamsFromPattern<P>
    : never;
  export type OtokRouteOptions<Path extends OtokRouteFilePattern> =
    import("@kamod-ch/otok/route").RouteBuildOptionsFor<Path>;
}

declare module "virtual:otok-route-redirect" {
  export type RedirectTarget =
    | "/articles"
    | "/login"
    | "/articles/:slug"
    | "/"
    | import("virtual:otok-routes").OtokRouteFilePattern;
}

export interface OtokRouteManifest {
  root: "/home/watzak/master/kamod/otok/examples/discussions-reference";
  routesDir: "src/app/routes";
  patterns: readonly import("virtual:otok-routes").OtokRouteFilePattern[];
  paths: readonly import("virtual:otok-routes").OtokRoutePath[];
}
