export {
  defineConfig,
  definePlugin,
  defineSetup,
  extractRuntimeConfig,
  mergeUserConfig,
  normalizePlugins,
  PluginContainer,
  resolveOtokConfig,
  validateSetupChanges,
  virtualModuleId,
} from "@otok/config";
export type {
  AppContext,
  BuildContext,
  ConfigSchema,
  DevServerContext,
  EnvSchema,
  OtokConfigEnv,
  OtokPlugin,
  OtokPluginFactory,
  OtokPluginInput,
  OtokRuntimeConfig,
  OtokUserConfig,
  PluginConfigContext,
  PluginResolvedContext,
  PluginSetupChange,
  PluginSetupContext,
  PluginSetupHook,
  PluginSetupResult,
  ResolvedOtokConfig,
  VirtualModuleFactory,
  ViteContext,
} from "@otok/config";
