export {
  assertAdapterCapability,
  defineAdapter,
  defineConfig,
  definePlugin,
  defineSetup,
  extractRuntimeConfig,
  hasAdapterCapability,
  mergeUserConfig,
  normalizePlugins,
  OTOK_ADAPTER_CAPABILITIES,
  PluginContainer,
  resolveOtokConfig,
  validateSetupChanges,
  virtualModuleId,
} from "@otok/config";
export type {
  AdapterBuildContext,
  AppContext,
  BuildContext,
  ConfigSchema,
  DevServerContext,
  EnvSchema,
  OtokAdapter,
  OtokAdapterCapability,
  OtokAdapterFactory,
  OtokAdapterInput,
  OtokConfigEnv,
  OtokPlugin,
  OtokPluginFactory,
  OtokPluginInput,
  OtokRuntime,
  OtokRuntimeConfig,
  OtokUserConfig,
  PluginConfigContext,
  PluginResolvedContext,
  PluginSetupChange,
  PluginSetupContext,
  PluginSetupHook,
  PluginSetupResult,
  ResolvedOtokAdapter,
  ResolvedOtokConfig,
  VirtualModuleFactory,
  ViteContext,
} from "@otok/config";
