/* eslint-disable */
// @generated by @kamod-ch/otok-route-typegen — do not edit manually.

/// <reference path="./src/app/routes/index.d.ts" />
/// <reference path="./src/app/routes/admin/posts/index.d.ts" />
/// <reference path="./src/app/routes/admin/posts/[slug].d.ts" />
/// <reference path="./src/app/routes/admin/posts/new.d.ts" />
/// <reference path="./src/app/routes/posts/[slug].d.ts" />
/// <reference path="./src/app/routes/_not-found.d.ts" />
/// <reference path="./src/app/routes/_error.d.ts" />
