/* eslint-disable */
// @generated by @kamod-ch/otok-route-typegen — do not edit manually.

declare module "virtual:otok-routes" {
  export type OtokRouteFilePattern = "/admin/posts/new" | "/admin/posts" | "/admin/posts/[slug]" | "/posts/[slug]" | "/";
  export type OtokRoutePath = "/admin/posts/new" | "/admin/posts" | "/admin/posts/:slug" | "/posts/:slug" | "/";
  export type OtokRouteParams<Path extends OtokRouteFilePattern> = Path extends infer P extends string
    ? import("@kamod-ch/otok/route").RouteParamsFromPattern<P>
    : never;
  export type OtokRouteOptions<Path extends OtokRouteFilePattern> = import("@kamod-ch/otok/route").RouteBuildOptionsFor<Path>;
}

declare module "virtual:otok-route-redirect" {
  export type RedirectTarget = "/admin/posts/new" | "/admin/posts" | "/admin/posts/:slug" | "/posts/:slug" | "/" | import("virtual:otok-routes").OtokRouteFilePattern;
}

export interface OtokRouteManifest {
  root: "/home/watzak/master/kamod/otok/examples/reference-flat-cms";
  routesDir: "src/app/routes";
  patterns: readonly import("virtual:otok-routes").OtokRouteFilePattern[];
  paths: readonly import("virtual:otok-routes").OtokRoutePath[];
}
