/* eslint-disable */
// @generated by @otok/route-typegen — do not edit manually.

/// <reference path="./src/app/routes/index.d.ts" />
/// <reference path="./src/app/routes/de/docs/[...slug].d.ts" />
/// <reference path="./src/app/routes/docs/[...slug].d.ts" />
