/* eslint-disable */
// @generated by @kamod-ch/otok-route-typegen — do not edit manually.

/// <reference path="./src/app/routes/index.d.ts" />
/// <reference path="./src/app/routes/employer/import/index.d.ts" />
/// <reference path="./src/app/routes/employer/import/[id].d.ts" />
/// <reference path="./src/app/routes/employer/jobs/index.d.ts" />
/// <reference path="./src/app/routes/employer/jobs/[id]/edit.d.ts" />
/// <reference path="./src/app/routes/employer/jobs/new.d.ts" />
/// <reference path="./src/app/routes/impressum.d.ts" />
/// <reference path="./src/app/routes/jobs/index.d.ts" />
/// <reference path="./src/app/routes/jobs/[slug].d.ts" />
/// <reference path="./src/app/routes/login.d.ts" />
