/* eslint-disable */
// @generated by @kamod-ch/otok-route-typegen — do not edit manually.

declare module "virtual:otok-routes" {
  export type OtokRouteFilePattern =
    | "/employer/jobs/new"
    | "/employer/jobs/[id]/edit"
    | "/employer/import"
    | "/employer/jobs"
    | "/employer/import/[id]"
    | "/impressum"
    | "/jobs"
    | "/login"
    | "/jobs/[slug]"
    | "/";
  export type OtokRoutePath =
    | "/employer/jobs/new"
    | "/employer/jobs/:id/edit"
    | "/employer/import"
    | "/employer/jobs"
    | "/employer/import/:id"
    | "/impressum"
    | "/jobs"
    | "/login"
    | "/jobs/:slug"
    | "/";
  export type OtokRouteParams<Path extends OtokRouteFilePattern> = Path extends infer P extends string
    ? import("@kamod-ch/otok/route").RouteParamsFromPattern<P>
    : never;
  export type OtokRouteOptions<Path extends OtokRouteFilePattern> =
    import("@kamod-ch/otok/route").RouteBuildOptionsFor<Path>;
}

declare module "virtual:otok-route-redirect" {
  export type RedirectTarget =
    | "/employer/jobs/new"
    | "/employer/jobs/:id/edit"
    | "/employer/import"
    | "/employer/jobs"
    | "/employer/import/:id"
    | "/impressum"
    | "/jobs"
    | "/login"
    | "/jobs/:slug"
    | "/"
    | import("virtual:otok-routes").OtokRouteFilePattern;
}

export interface OtokRouteManifest {
  root: "/home/watzak/master/kamod/otok/examples/devjobs-reference";
  routesDir: "src/app/routes";
  patterns: readonly import("virtual:otok-routes").OtokRouteFilePattern[];
  paths: readonly import("virtual:otok-routes").OtokRoutePath[];
}
