/* eslint-disable */
// @generated by @otok/route-typegen — do not edit manually.

/// <reference path="./src/app/routes/index.d.ts" />
/// <reference path="./src/app/routes/dashboard/index.d.ts" />
/// <reference path="./src/app/routes/dashboard/audit.d.ts" />
/// <reference path="./src/app/routes/dashboard/billing.d.ts" />
/// <reference path="./src/app/routes/dashboard/billing/portal.d.ts" />
/// <reference path="./src/app/routes/dashboard/team.d.ts" />
/// <reference path="./src/app/routes/invite/[token].d.ts" />
/// <reference path="./src/app/routes/login.d.ts" />
/// <reference path="./src/app/routes/org/new.d.ts" />
/// <reference path="./src/app/routes/register.d.ts" />
