/* eslint-disable */
// @generated by @otok/route-typegen — do not edit manually.

import type * as RouteModule from "../../../../../src/app/routes/_error";
import type {
  ExtractActionData,
  ExtractActionInput,
  ExtractLoaderData,
  ExtractMeta,
  ExtractSearchParams,
  RouteComponentProps,
  RouteErrorProps,
} from "otok/route";

declare module "./src/app/routes/_error" {
  export namespace Route {
    export type FilePattern = "/_error";
    export type Path = "/";
    export type Params = Record<string, never>;
    export type SearchParams = Record<string, string | string[] | undefined>;
    export type LoaderData = ExtractLoaderData<typeof RouteModule.loader>;
    export type ActionInput = ExtractActionInput<typeof RouteModule.action>;
    export type ActionData = ExtractActionData<typeof RouteModule.action>;
    export type Meta = ExtractMeta<typeof RouteModule.head, typeof RouteModule.meta>;
    export type ComponentProps = RouteComponentProps<LoaderData, ActionData, Params>;
    export type ErrorProps = RouteErrorProps<LoaderData, Params>;
    export type LayoutData = LoaderData;
    export type ParentData = Record<string, unknown>;
  }
}
