/* eslint-disable */
// @generated by @kamod-ch/otok-route-typegen — do not edit manually.

import type * as RouteModule from "../../../../../../src/app/routes/users/[id]";
import type {
  ExtractActionData,
  ExtractActionInput,
  ExtractLoaderData,
  ExtractMeta,
  ExtractSearchParams,
  RouteComponentProps,
  RouteErrorProps,
} from "@kamod-ch/otok/route";

declare module "./src/app/routes/users/[id]" {
  export namespace Route {
    export type FilePattern = "/users/[id]";
    export type Path = "/users/:id";
    export type Params = { id: string };
    export type SearchParams = Record<string, string | string[] | undefined>;
    export type LoaderData = ExtractLoaderData<typeof RouteModule.loader>;
    export type ActionInput = ExtractActionInput<typeof RouteModule.action>;
    export type ActionData = ExtractActionData<typeof RouteModule.action>;
    export type Meta = ExtractMeta<typeof RouteModule.head, typeof RouteModule.meta>;
    export type ComponentProps = RouteComponentProps<LoaderData, ActionData, Params>;
    export type ErrorProps = RouteErrorProps<LoaderData, Params>;
    export type LayoutData = LoaderData;
    export type ParentData = Record<string, unknown>;
  }
}
