type OtokRoutePrimitive = string | number | boolean;
type OtokRouteQueryValue = OtokRoutePrimitive | null | undefined | Array<OtokRoutePrimitive | null | undefined>;

type SplitRoute<Path extends string> = Path extends `/${infer Rest}` ? SplitRoute<Rest> : Path;
type SegmentParam<Segment extends string> = Segment extends `[[${infer Name}]]`
  ? { [Key in Name]?: OtokRoutePrimitive }
  : Segment extends `[...${infer Name}]`
    ? { [Key in Name]: OtokRoutePrimitive | OtokRoutePrimitive[] }
    : Segment extends `[${infer Name}]`
      ? { [Key in Name]: OtokRoutePrimitive }
      : {};
type MergeParams<Left, Right> = Left & Right;
type RouteParamsFromSegments<Path extends string> = Path extends `${infer Segment}/${infer Rest}`
  ? MergeParams<SegmentParam<Segment>, RouteParamsFromSegments<Rest>>
  : SegmentParam<Path>;
type RequiredKeys<T> = { [K in keyof T]-?: Record<string, never> extends Pick<T, K> ? never : K }[keyof T];
type RouteParams<Path extends string> = { [K in keyof RouteParamsFromSegments<SplitRoute<Path>>]: RouteParamsFromSegments<SplitRoute<Path>>[K] };
type RouteOptions<Path extends string> = {
  params?: RouteParams<Path>;
  query?: Record<string, OtokRouteQueryValue>;
  hash?: string;
};
type RouteOptionsFor<Path extends string> = RequiredKeys<RouteParams<Path>> extends never
  ? RouteOptions<Path> | undefined
  : Omit<RouteOptions<Path>, "params"> & { params: RouteParams<Path> };

declare module "virtual:otok-routes" {
  import type { OtokRoute } from "otok/server";

  // Ambient fallback: the runtime virtual module contains concrete values generated by Vite.
  export const routePaths: readonly string[];
  export const routeFilePatterns: readonly string[];
  export type OtokRoutePath = (typeof routePaths)[number];
  export type OtokRouteFilePattern = (typeof routeFilePatterns)[number];
  export type OtokRouteParams<Path extends string> = RouteParams<Path>;
  export type OtokRouteOptions<Path extends string> = RouteOptionsFor<Path>;
  export function route<Path extends string>(
    path: Path,
    ...args: RequiredKeys<RouteParams<Path>> extends never ? [options?: RouteOptions<Path>] : [options: RouteOptionsFor<Path>]
  ): string;
  export const routes: OtokRoute[];
  export const notFoundRoute: OtokRoute | undefined;
  export const errorRoute: OtokRoute | undefined;
}

declare module "virtual:otok-islands" {
  import type { IslandRegistry } from "otok/client";

  export const islandModules: IslandRegistry;
  export default islandModules;
}
